#server
spring.application.name=spring-app
server.port=9001

#db
fintech.dbuser = ${DB_USERNAME}
fintech.dbpass = ${DB_PASSWORD}
fintech.dburl = ${DB_URL}

#file management
# Set the maximum payload size to 10MB
#server.tomcat.max-http-form-post-size=10MB
#Maximum file size
spring.servlet.multipart.max-file-size=30MB
# Maximum request size
spring.servlet.multipart.max-request-size=30MB
#Enable multipart uploads
spring.servlet.multipart.enabled=true

#caching
spring.cache.cache-names=loanBalancesTrackerCache
spring.cache.caffeine.spec=maximumSize=10,expireAfterWrite=30m

#Monitoring (actuator)
management.server.port=9002
management.server.address=127.0.0.1
management.metrics.tags.application=${spring.application.name}
#management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.web.exposure.include=prometheus
# prevent sensitive info exposure
management.endpoint.health.show-details=never

#mailing settings
spring.mail.host=mail.pikipata.com
spring.mail.port=587
spring.mail.username=austine@pikipata.com
spring.mail.password=S9MogK%sIeU(9dpe
# Authentication and TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Important: Set the from address
spring.mail.properties.mail.smtp.from=austine@pikipata.com
# This prevents Spring from using localhost domain
spring.mail.properties.mail.smtp.localhost=pikipata.com
# Additional properties to ensure proper headers
spring.mail.properties.mail.smtp.allow8bitmime=true
#logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG




