spring.application.name=banking
server.port=9005

fintech.dbuser = remoteU
fintech.dbpass =12Ch@__@3g$
fintech.dburl = jdbc:mysql://159.223.194.128:3306/Pikipata

#security
spring.security.user.name=ncbaTester
spring.security.user.password=#ncba@Test1
securitySecretKey=G4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ
